### ISSUE TITLE
Jouele 3.x

### ISSUE THREAD

**Issue by eugene-lazarev** [beshur/wp-jouele#2]
Hi there!
Thanks for supporting this plugin. Do you have time to update this and use Jouele 3.x inside?

**Comment by beshur** [comment]
Hi @eugene-lazarev.
Maybe at some point I will upgrade it.

I do not use it myself, and also don't see any interest from the WP community.
"Active installations: Fewer than 10"

**Comment by eugene-lazarev** [comment]
Thank you, @beshur!
Actually from this point of view, nothing has changed in Jouele, it’s just about number of files (images, swf and additional jPlayer js-file has gone, only need to include one js and one css file).
The markup didn’t change: `<a href="{link_to_mp3}" class="jouele">{{song_name}}</a>`

**Comment by beshur** [comment]
Okay, thanks, I will take a look.

**Comment by beshur** [comment]
Released update as 0.2.0
